
enum LocalKeys {
	t_and = "t.and",
	t_business = "t.business",
	t_business_name = "t.business_name",
	t_conditions = "t.conditions",
	t_confirm = "t.confirm",
	t_confirm_password = "t.confirm_password",
	t_create = "t.create",
	t_create_new_business = "t.create_new_business",
	t_dont_have_a_naaraan_accont = "t.dont_have_a_naaraan_accont",
	t_email = "t.email",
	t_forgot_password = "t.forgot_password",
	t_free_trial = "t.free_trial",
	t_full_name = "t.full_name",
	t_help_center = "t.help_center",
	t_i_gree_to_the = "t.i_gree_to_the",
	t_log_in = "t.log_in",
	t_logout = "t.logout",
	t_or = "t.or",
	t_password = "t.password",
	t_password_doesnt_match = "t.password_doesnt_match",
	t_phone_number = "t.phone_number",
	t_please_choose_your_new_password = "t.please_choose_your_new_password",
	t_please_enter_your_email_to_request_a_password_reset = "t.please_enter_your_email_to_request_a_password_reset",
	t_profile = "t.profile",
	t_reset_password = "t.reset_password",
	t_select = "t.select",
	t_send = "t.send",
	t_sign_up = "t.sign_up",
	t_start_selling_with_naaraan = "t.start_selling_with_naaraan",
	t_terms = "t.terms",
	t_url_address = "t.url_address",
	t_url_address_caption = "t.url_address_caption",
}

export default LocalKeys
